### PR TITLE
Admin: Treasury Management: MIne Block with treasury is low

### LINKED ISSUE #14: A07 Admin: Treasury Management
Related to https://github.com/bitcoin-sv/bsv-faucet/issues/17 and https://github.com/bitcoin-sv/bsv-faucet/issues/13

Description:
For admins (role = 2) there will be a dedicated section /admin to allow them to see and manage the overall treasury.

Allow an admin to be able to view their amount, and hit a "Mine Block" function if their reserves run below 10 BSV.

This should initiate a fresh batch of BSV to the master treasury wallet.

- Show the total treasury reserves in the master wallet.
- Display in BSV and Satoshis
- Only allow the Mine Blocks function Display an alert if the balance is running low (below 10 BSV)

**Acceptance Criteria:**
0. Ensure the database schema structure is created and migration scripts run.

### PR DESCRIPTION
**Pull request by ikemHood**
may fix #14

### CODE REVIEW

**Comment by mo-jaber** [comment]
Hi @ikemHood can you resolve the conflicts as per the latest version of the code, as we have made some changes today

**Comment by ikemHood** [comment]
Done, will continue when dependencies are completed

**Comment by mo-jaber** [comment]
Hi @ikemHood could you update to reflect latest baseline? dependency https://github.com/bitcoin-sv/bsv-faucet/issues/17 is now in the latest version

**Comment by ikemHood** [comment]
Alright

**Pull request closed without merging**
