### PR TITLE
feat: added UI for admin to view all users

### PR DESCRIPTION
**Pull request by ShantelPeters**
I added the UI for admin to see all users on a table with the format (table columns): userid, email, type, date registered, total withdrawn (BSV), and actions (pause account or delete account)

### CODE REVIEW

**Comment by mo-jaber** [comment]
Hi @ShantelPeters this error has a whole heap of issues and it will not compile without errors..

Please fix

**Comment by mo-jaber** [comment]
@ShantelPeters 
image

**Comment by mo-jaber** [comment]
@ShantelPeters have commented all the lines of code out for you to re-do

image

**Comment by ShantelPeters** [comment]
> @ShantelPeters have commented all the lines of code out for you to re-do
> 
> image



> Hi @ShantelPeters this error has a whole heap of issues and it will not compile without errors..
> 
> Please fix

Okay sir .. will get straight to it..

**Comment by mo-jaber** [comment]
image

**Pull request merged**
