### PR TITLE
Feat/create treasury wallet

### PR DESCRIPTION
**Pull request by 0xdevcollins**
Please don’t close the PR just yet.

### CODE REVIEW

**Comment by 0xdevcollins** [comment]
@mo-jaber review my PR ser

**Comment by mo-jaber** [comment]
@0xdevcollins looks good. Can you resolve the conflicts for pnpm-lock.yaml then will complete merge

**Comment by 0xdevcollins** [comment]
> @0xdevcollins looks good. Can you resolve the conflicts for pnpm-lock.yaml then will complete merge

okay

**Comment by 0xdevcollins** [comment]
@mo-jaber resolved

**Comment by mo-jaber** [comment]
Thanks @0xdevcollins

**Comment by mo-jaber** [comment]
Hey @0xdevcollins 

Could you fix the following issues related to lib/wallet/

image

**Pull request merged**
